//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirjastoAppScrum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KirjastoProjektiEntities1 : DbContext
    {
        public KirjastoProjektiEntities1()
            : base("name=KirjastoProjektiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Kieli> Kieli { get; set; }
        public virtual DbSet<Koordinaatit> Koordinaatit { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Tekstit> Tekstit { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<InfoTekstit> InfoTekstit { get; set; }
        public virtual DbSet<Kuvat> Kuvat { get; set; }
    
        public virtual int PROC_Lis___Koordinaatit(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Lis___Koordinaatit", iDParameter);
        }
    
        public virtual int PROC_Poista_Ja_Siirra_Sub(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Poista_Ja_Siirra_Sub", iDParameter);
        }
    }
}
