//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirjastoAppScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koordinaatit
    {
        public int KoordinaattiID { get; set; }
        public Nullable<int> startX { get; set; }
        public Nullable<int> startY { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> radius { get; set; }
        public int kerros { get; set; }
        public Nullable<int> kuvaID { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Kuvat Kuvat { get; set; }
    }
}
