//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirjastoAppScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuvat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kuvat()
        {
            this.Koordinaatit = new HashSet<Koordinaatit>();
        }
    
        public int KuvaId { get; set; }
        public string AltText { get; set; }
        public string ImagePath { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koordinaatit> Koordinaatit { get; set; }
    }
}
