//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirjastoAppScrum.Models
{  
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Logins
    {
        [Required(ErrorMessage = "Anna käyttäjätunnus!")]
        public string Nimi { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Anna salasana!")]
        public string Hash { get; set; }
        public string Salt { get; set; }
        public string Rooli { get; set; }

        public virtual UserRoles UserRoles { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
