//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirjastoAppScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tekstit
    {
        public int TekstiID { get; set; }
        public string KieliID { get; set; }
        public string Teksti { get; set; }
        public Nullable<int> ReferTo { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Kieli Kieli { get; set; }
    }
}
